name: Pre-create Steamapps in ghcr.io
on:
  workflow_dispatch: {}
permissions:
  contents: read
  packages: write
jobs:
  # NB: Split up into multple jobs to avoid running out of disk space on the runner.
  pre-create-steamapps-in-ghcr:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repository:
          - abioticfactor
          - astroneer
          - corekeeper
          - enshrouded
          - palworld
          - satisfactory
          - valheim
    steps:
      - uses: actions/checkout@v6
      - uses: frantjc/actions/setup-tool@v1
        with:
          repository: dagger/dagger
          version: v0.19.8
      - shell: dagger {0}
        continue-on-error: true
        run: |
          test --module steamapps --backend registry://${{ github.actor }}:${{ github.token }}@ghcr.io/${{ github.repository }} --repository ${{ matrix.repository }} | combinedOutput
