name: Pre-create Steamapps in ghcr.io
on:
  workflow_dispatch: {}
permissions:
  contents: read
  packages: write
jobs:
  # NB: Split up into multple jobs to avoid running out of disk space on the runner.
  pre-create-steamapps-in-ghcr:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repository:
          - abioticfactor
          - astroneer
          - corekeeper
          - enshrouded
          - palworld
          - satisfactory
          - valheim
    steps:
      - uses: actions/checkout@v5
      - uses: dagger/dagger-for-github@v8.2.0
        env:
          DAGGER_NO_NAG: 1
        continue-on-error: true
        with:
          shell: |
            sindri-dev --module steamapps --backend registry://${{ github.actor }}:${{ github.token }}@ghcr.io/${{ github.repository }} | test --repository ${{ matrix.repository }} | combinedOutput
