name: Release
on:
  push:
    tags:
      # Rough semantic version regexp to only create releases
      # on complete semantic versions e.g. v1.0.0, but not v1.
      - v[0-9]+.[0-9]+.[0-9]+*
permissions:
  contents: read
  packages: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dagger/dagger-for-github@v8.2.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
          DAGGER_NO_NAG: 1
        with:
          shell: |
            withGhcrAuth() {
              $1 | withRegistryAuth ghcr.io ${{ github.actor }} env://GITHUB_TOKEN
            }
            tag=$(version)
            steamappsContainer=$(withGhcrAuth $(sindri-dev --module steamapps | container))
            wolfiContainer=$(withGhcrAuth $(sindri-dev --module wolfi | container))
            gitContainer=$(withGhcrAuth $(sindri-dev --module git | container))
            $steamappsContainer | publish ghcr.io/${{ github.repository }} &
            $steamappsContainer | publish ghcr.io/${{ github.repository }}:$tag &
            $steamappsContainer | publish ghcr.io/${{ github.repository }}:steamapps &
            $steamappsContainer | publish ghcr.io/${{ github.repository }}:$tag-steamapps &
            $wolfiContainer | publish ghcr.io/${{ github.repository }}:wolfi &
            $wolfiContainer | publish ghcr.io/${{ github.repository }}:$tag-wolfi &
            $gitContainer | publish ghcr.io/${{ github.repository }}:git &
            $gitContainer | publish ghcr.io/${{ github.repository }}:$tag-git &
            .wait
